version: "3.4"

x-base: &base
  image: loadimpact/k6
  stdin_open: true
  tty: true
  env_file: .env
  network_mode: host
  tmpfs:
    - /tmp
  volumes:
    - ./scripts:/scripts:ro

services:
  search-api:
    <<: *base
    command: "run /scripts/search-api.js"

  bookingcom-availability:
    <<: *base
    command: "run /scripts/bookingcom-availability.js"

  gphub-api:
    <<: *base
    command: "run /scripts/gphub-api.js"

  ratehawk-api:
    <<: *base
    command: "run /scripts/ratehawk-api.js"
