import http from 'k6/http';
import { check, group, sleep } from 'k6';
import { Rate } from 'k6/metrics';

export let options = {
  discardResponseBodies: false,
  scenarios: {
    searches: {
      executor: 'ramping-vus',
      stages: [
        { duration: '3m', target: 36 }, // simulate ramp-up of traffic from 1 to 50 users over 3 minutes.
        { duration: '7m', target: 36 }, // stay at 50 users for 7 minutes
        { duration: '2m', target: 0 }, // ramp-down to 0 users
      ],
      gracefulRampDown: '60s',
      gracefulStop: '60s'
    }
  },
  thresholds: {
    http_req_duration: ['p(99)<50000'], // 99% of requests must complete below 50s
    errors: ['rate<0.01'], // <1% errors
    hotels: ['rate>0.99'],
  }
};

export function ISODateString(d) {
  function pad(n) {
    return n < 10 ? '0' + n : n
  }
  return d.getUTCFullYear() + '-' + pad(d.getUTCMonth() + 1) + '-' + pad(d.getUTCDate());
}

export function addDays(date, days) {
  let result = new Date(date);
  result.setDate(result.getDate() + days);
  return result;
}

const AUTHORIZATION = __ENV.RH_AUTHORIZATION_HEADER
const BASE_URL = 'https://api.worldota.net/api/b2b/v3/search/serp/hotels/';

const BASE_PARAMS = {
  residency: 'gb',
  language: 'en',
  guests: [
    {
      'adults': 2,
      'children': []
    }
  ],
  ids: [
    'hotel_indigo_london_1_leicester_square',
    '2br_apt_w_garden_near_clapham_high_street_station',
    '1_bedroom_property_near_hyde_park',
    'portway_gem',
    'european_hotel_2',
    'large_3br_flat_in_canary_wharf_for_up_to_6',
    'stunning_loft_apartment_central_soho_3_bedrooms_2_bath_office',
    '4_bedroom_mews_house_in_kensal_rise',
    'london_apartments_camden_town_area',
    '287_green_lanes_',
    'urban_stay_shard_view_apartments',
    '1_bedroom_apartment_in_sloane_square',
    '1_bedroom_flat_in_bethnal_green',
    'bazely_street_deluxe_single_room_4',
    'the_penthouse_25',
    'the_residence_stepney',
    'the_grand_hotel_21',
    'the_jade',
    'grange_blooms_town_house_hotel',
    'trendy_3br_flat_in_notting_hill',
    'forest_view_hotel',
    'new_super_3bd_family_home_stunning_london_views',
    '2_bedroom_apartment_in_borough',
    'hallmark_hotel_croydon_2',
    'spacious_4_bedroom_for_8_guests_in_central_london',
    '1_bedroom_flat_near_marble_arch',
    '1_bedroom_flat_in_notting_hill',
    'park_hotel_ilford',
    '2_bedroom_apartment_in_central_london_2',
    'hip_2_bedroom_flat_near_peckham_high_street',
    'the_diplomat_hotel',
    'sleeps4_beautiful_studio_euston_3',
    '1_bedroom_apartment_near_brick_lane',
    '2_bedroom_apartment_near_kensington_olympia_station',
    'stay_at_mine_greek_street',
    'holiday_inn_london_west',
    'saltwell_street_deluxe_en_suite_room',
    'the_grange_pub',
    '1_bedroom_flat_in_south_kensington_2',
    '2_bed_in_amazing_west_london_location',
    '1_bedroom_pimlico_flat_near_victoria_station',
    'stylish_rooftop_flat_on_kensington_high_street',
    'hotel_indigo_london_tower_hill',
    'spacious_studio_in_central_location_in_westminster',
    '3_bedroom_house_with_garden_in_brixton',
    '2_bedroom_flat_in_canada_water',
    'gresham_hotel',
    'goddis_lodge',
    'ivy_house_2',
    'ilford_apartments_3',
    '1_bedroom_apartment_near_st_pauls_2',
    '1_bedroom_apartment_in_limehouse_london',
    'saco_fleet_street__crane_court',
    'flexistay_sutton_aparthotel',
    'the_pride_of_paddington',
    'walk_drive_deluxe_guest_room_1',
    '1_bedroom_apartment_near_marylebone',
    'rhodes_hotel',
    'the_park_hotel_4',
    '1_bedroom_apartment_in_knightsbridge',
    '4_storey_house_in_dalston',
    'the_moorgate',
    'st_georges_hotel_wembley',
    'corner_green_guesthouse',
    'angus_hotel_3',
    '2_bedroom_flat_in_greenwich',
    '45_park_lane',
    'modern_family_home_close_to_victoria_station',
    'acton_hill_hotel',
    'the_mayflower_hotel_apartments',
    'shandon_house',
    'holiday_inn_express_london__park_royal',
    'devonshire_hotel',
    'best_western_chiswick_palace_',
    '2_beds_edgware_road_apartment',
    'the_black_lion',
    'thistle_kensington_gardens',
    'the_luxury_inn',
    '1n_student_hotel_camden_students_only',
    '1_bedroom_apartment_in_hammersmith',
    '_0x3f9c7',
    'beaufort_house_knightsbridge',
    'cogie_house',
    'flat_2_broad_court',
    'savoro_restaurant_with_rooms',
    'i_dwell_dartford_house',
    '2_bedroom_flat_in_whitechapel',
    '1_bedroom_flat_near_tower_bridge',
    'luxurious_2bed_apt_5_mins_from_buckingham_palace',
    'montagu_place_hotel',
    'tower_bridge_accommodation_22',
    'alfred_place_1',
    'atini_guest_house',
    'fitzrovia_belle_public_house_hotel',
    'metropolitan_by_como',
    'amhurst_hotel',
    '2_bed_terrace_apartment_in_notting_hill',
    'apartment_pillfold_westminster',
    'holland_park_lifestyle',
    'park_plaza_victoria_london',
    '2_bedroom_flat_near_notting_hill_2',
    '44_curzon_street',
    '1_bedroom_fitzrovia_apartment_10minute_walk_from_oxford_street_soho_2',
    'well_connected_cosy_2_bedroom_home',
    'tower_of_london_private_bedrooms',
    'o_hyde_park',
    'stylish_1_bedroom_studio_near_canary_wharf',
    'super_2_bed_flat_in_centre_portobello_notting_hill',
    '_0x27f4a',
    'st_georges_lodge_3',
    'the_bryson_hotel',
    'bridge_house_apartment',
    'saco_apartments_hammersmith',
    'urban_chic_chiltern_and_baker',
    'aloft_london_excel',
    'the_grand_at_trafalgar_square_2',
    'the_hallam',
    'warm_east_london_apartment_sleeps_4',
    'apple_house_guest_house_heathrow_airport',
    'aldgate_apartments_2',
    'aircondition_2_beds_2_baths_victoria_station',
    'hellenic_hotel_london',
    '130_queens_gate_apartments',
    '3_bedrooms_apartment_central_london',
    '2_bedroom_house_with_roof_terrace',
    'the_z_hotel_city',
    'the_fusilier_inn',
    'the_chelsea_arms_bright_3bdr_with_garden_private_parking_2',
    'forest_in_city_lodge',
    'apple_apartments_canary_wharf',
    'flemings_mayfair',
    'adria_boutique_hotel',
    '397_oxford_street_apartments',
    'the_firs_lodge_hotel',
    '26_penge_house',
    '1_bedroom_flat_near_hampstead_heath_3',
    'bridge_park_hotel',
    'best_western_ilford',
    'al_fresco_dream',
    '1_bedroom_flat_in_knightsbridge_sleeps_2',
    'veeve_apartment_cheyne_row_chelsea',
    'primrose_family_fun',
    'the_henrietta_hotel',
    'one_aldwych',
    'alexandra_hotel_2',
    '1_doublebed_kenningtonsk',
    '69thegrove',
    'the_luxe_mayfair_house',
    'roomspace_serviced_apartments__the_courtyard',
    '2_bedroom_flat_in_west_kensington',
    '2_bedroom_apartment_near_queens_park_2',
    'charming_peaceful_2_bed_with_parking_and_garden',
    'ibis_london_heathrow_airport',
    'the_hurdwick',
    'a_modern_comfy_newly_remodeled_2bd_house',
    'st_georges_hotel_3',
    'luxury_studio_apart_piccadilly_circus',
    'royal_garden_hotel_2',
    '3461_london',
    'heathrow_inn_2',
    'anson_house_deluxe_guest_room_2',
    '1_bedroom_flat_near_regent39s_park',
    '1_bedroom_victorian_flat_in_stoke_newington',
    'westciti_caroco_aparthotel',
    'messina_studios',
    'sofitel_london_heathrow',
    'the_parkcity_hotel',
    'the_chelsea_pelham_retreat_kbw',
    'velvet_2bedroom_apartment_brewery_road',
    '2_bedroom_flat_in_mayfair',
    'the_sanctuary_house_hotel',
    'king_solomon_hotel',
    '1_bedroom_flat_in_islington_with_a_garden',
    'the_chelsea_cathcart_lodge_pc01',
    'the_bridge_inn_3',
    'luxury_holborn_1_bedroom_flats',
    '1_bedroom_apartment_in_vibrant_putney',
    'skyvillion_tower_points',
    'stylish_2_bedroom_maisonette_in_victoria',
    '3_beds2baths_oxford_circus',
    'dorsett_city_london',
    'stratford_house_',
    'grantly_hotel',
    'the_britten_street_studio_hbg2',
    'andora_apartments_2',
    '2_bedroom_flat_near_notting_hill',
    'new_road_hotel',
    'marlin_apartments_stratford',
    '11_tottenham_mews',
    'deluxe_central_london_apartmentssouthwark',
    'albany_hotel_4',
    'london_plus_heathrow',
    'lovely_studio_wbalcony_in_islington_4_guests',
    'bexley_village_hotel',
    'london_city_suites_2',
    '3_bedroom_marylebone_ground_floor_flat',
    '2_bedrooms_apartment_2_central_london',
    '2_bedroom_apartment_in_pimlico_london',
    '3_bedroom_family_home_next_to_southfields',
    'somerville_apartments_london_heathrow',
    'amsterdam_hotel_london',
    '2_bedroom_apartment_in_quite_central_london',
    '2bedroom_portobellonotting_hill_apartment',
    '1_bedroom_flat_with_panoramic_view_of_piccadilly_circus',
    'norfolk_towers_paddington',
    'mentone_hotel',
    'the_re_london_shoreditch',
    'good_hotel_london',
    'house_close_to_kings_cross',
    '1_bedroom_flat_in_vauxhall_near_tube',
    '3_bedroom_house_in_the_heart_of_shoreditch',
    'shangri_la_hotel_at_the_shard_london',
    'vive_unique_victorian_house_fulham',
    'stylish_3bed_flat_w_balcony_is_west_kensington',
    'abc_hyde_park_hotel',
    'the_tulse_hill_hotel',
    '2_bedroom_apartment_in_notting_hill_2',
    '274_suites',
    'the_rembrandt__a_sarova_hotel',
    'angel_sophistication',
    '23_',
    'amazing_2_bed_just_minutes_from_paddington',
    'algate_apartment',
    '1_bedroom_chelsea_flat_2',
    'hotel_xanadu',
    'london_hilton_on_park_lane',
    'sloane_apartments',
    '56_welbeck_street',
    'ridgeway_hotel',
    'spacious_1_bedroom_flat_in_victoria',
    'the_birdsnest_guest_house',
    'hyde_park_superior_apartments',
    '6_portobello_road',
    'lancaster_london',
    '1_bedroom_apartment_in_islington_with_balcony',
    '3_beds_apartment_near_euston_by_city_stay_london',
    'the_arch_london',
    'new_dome',
    'doubletree_by_hilton_london__ealing_hotel',
    '1_bedroom_apartment_in_notting_hill_accommodates_2',
    'islington_chic_apartment',
    'the_william_iv_2',
    'kings_cross_deluxe_serviced_apartments',
    '2_bedroom_flat_with_private_garden_east_london',
    'urban_stay_fitzrovia_apartments',
    'the_bank_hotel_2',
    'otel_bridge_rooms',
    'modern_studio_apartment_in_chelsea',
    '17_hertford_street',
    'grange_tower_bridge',
    'the_stafford_london_by_kempinski',
    'rez_apart_hotel',
    '38_whitehall_road',
    'goodwood_hotel',
    'holiday_inn_express_london__newbury_park',
    '54_courtfield_gardens',
    'emerald_apartments_london',
    '1_bedroom_primrose_hill_apartment',
    'sheriff_hotel_2',
    'notting_hill_maisonette',
    'london_guest_house_2',
    '2_bedroom_apartment_near_kings_cross',
    '30_nights_minimum_stay_the_chelsea_edith_grove_lodge',
    'pullman_london_st_pancras_2',
    '1_bedroom_flat_in_wandsworth',
    'stylish_apartment12_minutes_from_oxford_streetcentral_londonacfree_wifi',
    '2_bed_lux_apartment_near_central_london_free_wifi',
    'marble_apartments_tooting_house',
    'holiday_inn_express_london_wandsworth',
    'the_ship_inn_7',
    'cavendish_house_3',
    'studios2let__north_gower',
    'fulham_3_bedroom_apartment',
    'saint_james_westminster',
    '3bedroom_mews_house_with_garden',
    '1_bedroom_apartment_in_battersea_with_roof_terrace',
    'veeve_grand_7_bed_georgian_house_on_kennington_road_near_waterloo',
    'west_kensington_stunning_2_bedroom_flat_with_balcony',
    'holiday_inn_express_london__limehouse',
    '1_bedroom_apartment_in_shoreditch_5',
    'grenville_hotel',
    'apple_house_guesthouse_wembley',
    'amity_hostel',
    '1_bedroom_apartment_in_heart_of_shepherds_bush_accommodates_4',
    'the_wellington',
    'chic_and_cosy_2_bedroom_flat_by_earls_court_tube',
    'marlyn_lodge_city_of_london',
    'town_hall_hotel__apartments',
    '3_bedroom_apartment_with_views',
    'turnpike_house',
    '2_bedroom_flat_in_shoreditch_2',
    'the_commongate',
    'the_kings_arms_6',
    'southwark_serviced_apartments',
    'stunning_knightsbridge_suites_by_sonder',
    '2_bedroom_apartment_in_aldgate_east',
    'ibis_styles_hounslow',
    'holiday_inn_express_london__croydon',
    '39_suites',
    'new_2bd_east_london_flat_with_garden_woodford_2'
  ],
  currency: 'EUR'
};

export let errorRate = new Rate('errors');
export let hotelsRate = new Rate('hotels');


export default () => {
  let dateParams = {
    checkin: ISODateString(addDays(new Date(), 1)),
    checkout: ISODateString(addDays(new Date(), 2))
  };
  let hotelsParams = Object.assign(dateParams, BASE_PARAMS);

  let res = http.post(
    BASE_URL,
    JSON.stringify(hotelsParams),
    {
      headers: {
        'Content-Type': 'application/json',
        'Authorization': AUTHORIZATION,
      }
    }
  );

  let result = check(res, {
    'status is 200': (r) => r.status == 200,
  });
  errorRate.add(!result);


  if (result) {
    let hotelObjects = res.json();

    let hotelsCheck = check(hotelObjects, { 'hotels available': (obj) => obj['data']['total_hotels'] > 0 });
    hotelsRate.add(hotelsCheck);
  }

  sleep(1);
};
